apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent
  namespace: security-lab
spec:
  selector:
    matchLabels:
      app: elastic-agent
  template:
    metadata:
      labels:
        app: elastic-agent
    spec:
      serviceAccountName: default
      containers:
      - name: elastic-agent
        image: docker.elastic.co/beats/elastic-agent:8.11.0
        env:
        - name: FLEET_URL
          value: "http://elasticsearch:9200"
        - name: FLEET_ENROLL
          value: "true"
        - name: FLEET_INSECURE
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: etc
          mountPath: /hostfs/etc
          readOnly: true
        - name: var-log
          mountPath: /hostfs/var/log
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: etc
        hostPath:
          path: /etc
      - name: var-log
        hostPath:
          path: /var/log
