apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: security-lab
data:
  elasticsearch.yml: |
    cluster.name: "security-lab"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: true
    xpack.security.authc:
      anonymous:
        username: anonymous_user 
        roles: superuser
        authz_exception: true
